import { type ProjectInfo } from "./interfaces";

export const projects: ProjectInfo[] = [
  {
    id: 1,
    title: "py_flags",
    description: "CLI flags parser library for python.",
    skills: [
      "Object-Oriented Programming (OOP)",
      "Strict typing in python, using mypy to check",
      "API design for dev tools",
    ],
    languagesAndFrameworks: ["Python"],
    additionalInfo: "",
    projectUrl: "https://github.com/meee-low/py_flags",
    imagePath: "/img/projects/py_flags_cropped.webp",
    highlighted: false,
    hidden: false,
    filterableTags: ["Python"],
  },
  {
    id: 2,
    title: 'Better "Daily Drive" for Spotify',
    description:
      "Grabs tracks and podcast episodes from various sources and merges them in a single playlist. The goal is to approximate a radio station, with different themed blocks.",
    skills: ["Direct interaction with RESTful API"],
    languagesAndFrameworks: ["Python", "SpotifyAPI"],
    additionalInfo: "",
    projectUrl: "https://github.com/meee-low/spotify-api",
    imagePath: "/img/projects/betterspotifydailydrive.webp",
    highlighted: false,
    hidden: false,
    filterableTags: ["Python", "Backend/CLI"],
  },
  {
    id: 3,
    title: "Web of Marvel Characters",
    description:
      "Visualizes a network of Marvel characters based on their common appearances in the comics.",
    skills: [
      "Web scraping",
      "Data cleaning and processing",
      "Graph network visualization",
    ],
    languagesAndFrameworks: [
      "Python",
      "BeautifulSoup4",
      "Pandas",
      "Jupyter Notebook",
    ],
    additionalInfo: "",
    projectUrl: "https://github.com/meee-low/web-of-marvel-characters",
    imagePath: "/img/projects/web-of-marvel_cropped.webp",
    highlighted: true,
    hidden: false,
    filterableTags: ["Python", "Data", "Business"],
  },
  {
    id: 4,
    title: "Portfolio",
    description: "The website you are probably reading right now!",
    skills: ["Front-end design", "Semantic HTML"],
    languagesAndFrameworks: ["TypeScript", "React", "HTML", "CSS"],
    additionalInfo: "",
    projectUrl: "https://github.com/meee-low/new-portfolio",
    imagePath: "/img/projects/youarehere.webp",
    highlighted: false,
    hidden: false,
    filterableTags: ["Other"],
  },
  {
    id: 5,
    title: "Exploration of Biases in Critics vs. Public Movie Reviews",
    description: "",
    skills: ["Data analysis"],
    languagesAndFrameworks: ["Python", "Pandas", "Jupyter Notebook"],
    additionalInfo: "",
    projectUrl:
      "https://www.kaggle.com/milofd/rottentomatoes-critics-vs-audiences-reviews",
    imagePath: "/img/projects/kaggle-movies-critics-genre_cropped.webp",
    highlighted: true,
    hidden: false,
    filterableTags: ["Python", "Data", "Business"],
  },
  {
    id: 6,
    title: "Other Small Projects",
    description:
      "Projects too small for their own repo. Usually mathematical visualization, competitive programming problems or exploring new programming languages.",
    skills: [
      "Mathematical visualization",
      "Problem solving and algorithms",
      "Exploring new tools",
      "Adapting to new problems and tools",
    ],
    languagesAndFrameworks: [
      "Python",
      "Rust",
      "C++",
      "Golang",
      "Julia",
      "Matplotlib",
      "Numpy",
      "PyGame",
    ],
    additionalInfo: "",
    projectUrl: "https://github.com/meee-low/challenges",
    imagePath:
      "/img/projects/challenges_mandelbrot-removebg-preview_cropped.webp",
    highlighted: false,
    hidden: false,
    filterableTags: ["Other", "Fun"],
  },
  {
    id: 7,
    title: "Video Game Market Tracker",
    description:
      "A spreadsheet that gathers user input on the market prices, graphs trends and recommends actions related to production.",
    skills: [
      "Pivot tables",
      "Advanced spreadsheet manipulation",
      "Data visualization",
      "Operational recommendations",
    ],
    languagesAndFrameworks: ["MS Excel", "Google Sheets", "Google Forms"],
    additionalInfo: "",
    projectUrl: "",
    imagePath: "/img/projects/spreadsheeet.webp",
    highlighted: false,
    hidden: false,
    filterableTags: ["Business"],
  },
  {
    id: 8,
    title: "Jurnalo",
    description:
      "A CLI journal, mood tracker and habit tracker built in Rust (WIP).",
    skills: [
      "ORM - Object Relational Mapping",
      "Backend development",
      "SQL Relational Databases",
      "Serialization and deserialization",
    ],
    languagesAndFrameworks: ["Rust", "Diesel", "Serde", "SQLite"],
    additionalInfo: "",
    projectUrl: "https://github.com/meee-low/jurnalo/",
    imagePath: "/img/projects/jurnalo-mock.webp",
    highlighted: true,
    hidden: false,
    filterableTags: ["Backend/CLI"],
  },
];
