name: Build and Deploy Svelte Website

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Build Svelte website
      run: npm run build

    - name: Get current timestamp
      id: get-timestamp
      run: echo "timestamp=$(date + '%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Commit and push changes
      env:
        TIMESTAMP: ${{env.timestamp}}
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add docs/
        git commit -m "Automatic build in /docs at ${{ env.timestamp }}"
        git push